# Generated by Django 4.1 on 2022-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='featured',
        ),
        migrations.AddField(
            model_name='users',
            name='confirmpassword',
            field=models.TextField(default=True, max_length=120),
            preserve_default=False,
        ),
    ]
