# Generated by Django 4.1 on 2022-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_featured_users_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='types',
            field=models.TextField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
